import fs from 'fs';
import path from 'path';
import type { AstroConfig, AstroIntegration } from 'astro' with { "resolution-mode": "import" };
import { fileURLToPath } from 'url';

/**
 * Shape of the configuration object whose key/values will be embedded as custom constants.
 */
export interface BuildTimeConstantsConfigType {
  [key: string]: unknown;
}

/**
 * Optional runtime parameters that control how the integration writes the generated file.
 */
export interface BuildTimeConstantsOptions {
  outputFile?: string;
  now?: Date;
}

/**
 * Default path (from the Astro project root) where the generated module will be saved.
 */
export const DEFAULT_OUTPUT_FILE = './src/astro-build-time-constants.ts';

const GENERATED_HEADER = '// Generated by astro-build-time-constants';

/**
 * Stringifies the custom config keys so that we can inline them directly in TS source.
 */
function formatCustomConfig(buildTimeConstantsConfig: BuildTimeConstantsConfigType): string {
  return JSON.stringify(buildTimeConstantsConfig, null, 2).replace(/\n/g, '\n  ');
}

/**
 * Produces the contents of the generated Astro module, embedding both time and custom data.
 */
export function createAstroBuildTimeModule(
  buildTimeConstantsConfig: BuildTimeConstantsConfigType = {},
  now: Date = new Date(),
): string {
  const epoch = Math.round(now.getTime() / 1000);

  return [
    GENERATED_HEADER,
    '',
    "export const digits2 = (number: number) => (number < 10 ? '0' + number : '' + number)",
    'export const astroBuildTimeConstants = {',
    '  internal: {',
    `    epoch: ${epoch},`,
    `    seconds: ${now.getUTCSeconds()},`,
    `    minutes: ${now.getUTCMinutes()},`,
    `    hours: ${now.getUTCHours()},`,
    `    fullYear: ${now.getUTCFullYear()},`,
    `    month: ${now.getUTCMonth() + 1},`,
    `    date: ${now.getUTCDate()},`,
    `    iso: "${now.toISOString()}",`,
    '  },',
    `  custom: ${formatCustomConfig(buildTimeConstantsConfig)},`,
    '}',
    '',
  ].join('\n');
}

/**
 * Generates (and writes) the Astro module, returning the absolute file path for observability.
 */
export function runAstroBuildTimeConstants(
  buildTimeConstantsConfig: BuildTimeConstantsConfigType = {},
  options: BuildTimeConstantsOptions = {},
): { filePath: string } {
  const filePath = options.outputFile ?? DEFAULT_OUTPUT_FILE;
  const now = options.now ?? new Date();
  const fileContents = createAstroBuildTimeModule(buildTimeConstantsConfig, now);

  fs.mkdirSync(path.dirname(filePath), { recursive: true });
  fs.writeFileSync(filePath, fileContents);
  console.log(`Generate ${filePath}`);

  return { filePath };
}

/**
 * Resolves the default output file relative to the Astro config paths.
 */
function resolveAstroOutputFile(astroConfig: AstroConfig): string {
  const srcDirUrl = astroConfig.srcDir ?? new URL('./src/', astroConfig.root);
  const outputFileUrl = new URL('./astro-build-time-constants.ts', srcDirUrl);
  return fileURLToPath(outputFileUrl);
}

/**
 * Astro integration entry point that wires the hook to generate the module after config is loaded.
 */
export default function buildTimeConstants(
  buildTimeConstantsConfig: BuildTimeConstantsConfigType = {},
): AstroIntegration {
  return {
    name: 'astro-build-time-constants',
    hooks: {
      'astro:config:done': ({ config }: { config: AstroConfig }) => {
        const outputFile = resolveAstroOutputFile(config);
        runAstroBuildTimeConstants(buildTimeConstantsConfig, { outputFile });
      },
    },
  };
}
